[tool.poetry]
name = "src"
version = "0.1.0"
description = ""
authors = ["JBusink <94122040+JBusink@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
pyvisa = "^1.12.0"
matplotlib = "^3.6.2"
pyvisa-py = "^0.5.3"
pyserial = "^3.5"
arduino-device = "^1.0.1"
numpy = "^1.23.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
view = "src.pythondaq.view:main"
histogram = "src.pythondaq.view:histogram"
ID = "src.pythondaq.view:identification"
